### PR TITLE
Make IsFunctionTemplate and IsObjectTemplate part of v8::internal

### PR DESCRIPTION
**Pull request by nikhilm**
See https://github.com/zpao/v8monkey/issues/90

This is what I assumed sdwilsh meant when he said they should be moved to v8::internal.
They are no longer members of the respective classes.

### CODE REVIEW

**Comment by sdwilsh** [comment]
If you can rebase and address these comments, we'll be happy to take this change.  Thanks so much for the patch!

**Comment by sdwilsh** [comment]
I nearly forgot!  We plan on licensing these files under the three clause BSD license or the [mozilla tri-license](https://www.mozilla.org/MPL/boilerplate-1.1/), but haven't figured out which one we need to use, so there's nothing in the files.  Are you OK with these possible licenses for your code?

**Comment by nikhilm** [comment]
yes I'm fine with the licensing.

**Comment by nikhilm** [comment]
sorry about the late update, was settling in at Mozilla :)

**Comment by sdwilsh** [comment]
No worries.  One of us should look at this either today or tomorrow.

**Comment by nikhilm** [comment]
ping!

**Comment by sdwilsh** [comment]
If you can update this so it can automagically be merged, that'd be awesome.  Sorry this took so long, but I'm transitioning to a new job and was really hoping that @robarnold or @zpao could do this before I could.

**Comment by nikhilm** [comment]
Updated

**Pull request merged**
